# Your workflow name.
name: Deploy to Render

# Run workflow on every push to main branch.
on:
  push:
    branches: [main]

# Workflow jobs.
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Check out your repository.
      - name: Checkout
        uses: actions/checkout@v2

      # Log in to Docker Hub (Optional: required only if you're using a private Docker registry)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build your Docker container.
      - name: Build Docker image
        run: docker build -t keerthanaconnect/my-app:latest

      # Push Docker image to Docker Hub (Optional: required only if you're using a private Docker registry)
      - name: Push Docker image to Docker Hub
        run: docker push keerthanaconnect/my-app:latest

      # Deploy Docker image to Render via API
      - name: Deploy to Render
        run: |
          curl -X POST \
            -H "Accept: application/json" \
            -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
            -H "Content-Type: application/json" \
            -d '{
              "serviceId": "<YOUR_RENDER_SERVICE_ID>",
              "clearCache": false
            }' \
            https://api.render.com/v1/services/<YOUR_RENDER_SERVICE_ID>/deploys